=== HL7/JIRA-Spec-Artifacts/schemas/specification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  When this schema is changed, the following code must be updated to align:
  - Scriptrunner REST Endpoints: uploadBallotSpreadsheet
  - BALDEF Workflow (2 classes x 2 locations)
  - SPEC Workflow (1 class)
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="workgroups.xsd"/>
  <xs:element name="specification">
    <xs:annotation>
      <xs:documentation>All content related to a single HL7 specification.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="version" minOccurs="1" maxOccurs="unbounded">
          <xs:annotation>
            <xs:documentation>Indicates an official major published release version.  (Technical correction releases are not tracked.)  Used to identify list of allowed versions when tracking version issue is raised in and fixed in.</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:attribute name="code" type="xs:NMTOKEN" use="required">
              <xs:annotation>
                <xs:documentation>The code to display for the version</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="url" type="website" use="optional">
              <xs:annotation>
                <xs:documentation>The persistant URL associated with this version of the specification.  Used in URL validation.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="deprecated" type="xs:boolean" default="false">
              <xs:annotation>
                <xs:documentation>If true, indicates that the version will not be available for selection as a 'reported version' when submitting new issues.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
        <xs:element name="artifactPageExtension" minOccurs="0" maxOccurs="unbounded">
          <xs:annotation>
            <xs:documentation>Indicates suffixes that might be associated with pages generated for artifacts.  Used for checking/populating artifacts based on URLs entered for the tracker</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:attribute name="value" type="xs:NMTOKEN" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="artifact" minOccurs="0" maxOccurs="unbounded">
          <xs:annotation>
            <xs:documentation>A formal artifact that can be referenced as part of feedback on a specification</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="otherArtifact" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                  <xs:documentation>Indicates additional artifacts whose issues should be reported under the parent artifact</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:attribute name="id" type="NonEmptyString" use="required">
                    <xs:annotation>
                      <xs:documentation>The formal identifier for the artifact whose issues are to be reported under the parent artifact</xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="key" type="xs:NMTOKEN" use="required">
              <xs:annotation>
                <xs:documentation>The key used inside Jira to identify the artifact.  This key must not be renamed and cannot be removed if it appears in any tracker item.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="name" type="Name" use="required">
              <xs:annotation>
                <xs:documentation>The name to display to users for the artifact.  This can change if the artifact is renamed</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="id" type="NonEmptyString" use="optional">
              <xs:annotation>
                <xs:documentation>The formal identifier associated with the artifact (if there is one).  OID for CDA templates, ResourceType/id for FHIR, etc.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="workgroup" type="WorkGroup" use="optional">
              <xs:annotation>
                <xs:documentation>The work group typically responsible for issues relating to this artifact</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="deprecated" type="xs:boolean" default="false">
              <xs:annotation>
                <xs:documentation>If true, indicates that the artifact can no longer be associated with newly raised issues, but it can still appear on old issues and be used in search</xs:documentation>
              </xs:annotation>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
        <xs:element name="page" maxOccurs="unbounded">
          <xs:annotation>
            <xs:documentation>Indicates a documentation page that's not tightly associated with an artifact</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="otherpage" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                  <xs:documentation>Additional page URLs that should be treated as part of this page for categorization purposes (used to infer/validate pages based on URL)</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:attribute name="url" type="xs:NMTOKEN" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="key" type="xs:NMTOKEN" use="required">
              <xs:annotation>
                <xs:documentation>The key used inside Jira to identify the page  This key must not be renamed and cannot be removed if it appears in any tracker item.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="name" type="Name" use="required">
              <xs:annotation>
                <xs:documentation>The name to display to users for the page.  This can change if the page is renamed</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="workgroup" type="WorkGroup" use="optional">
              <xs:annotation>
                <xs:documentation>The work group typically responsible for issues relating to this page</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="deprecated" type="xs:boolean" default="false">
              <xs:annotation>
                <xs:documentation>If true, indicates that the page can no longer be associated with newly raised issues, but it can still appear on old issues and be used in search</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="url" type="xs:NMTOKEN" use="optional">
              <xs:annotation>
                <xs:documentation>The primary url associated with this page (this may initially be the same as the key, but will change if the url changes)</xs:documentation>
              </xs:annotation>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="url" type="website" use="optional">
        <xs:annotation>
          <xs:documentation>The official URL for this specification.  Used when validating URLs</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="ciUrl" type="website" use="optional">
        <xs:annotation>
          <xs:documentation>The continuous integration build URL for this specification.  Used when validating URLs</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="ballotUrl" type="website" use="optional">
        <xs:annotation>
          <xs:documentation>The URL for the current/most recent ballot of this specification.  Used when validating URLs</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="gitUrl" type="website" use="optional">
        <xs:annotation>
          <xs:documentation>The base URL for the repository in which the source material for this specificaiton is maintained.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="defaultWorkgroup" type="WorkGroup" use="optional">
        <xs:annotation>
          <xs:documentation>The work group typically associated with issues raised against this specification if a more specific work group isn't determined based on pages or artifacts</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="defaultVersion" type="xs:NMTOKEN" use="required">
        <xs:annotation>
          <xs:documentation>The version to identify as the 'raised' version for an issue if not overridden by the submitter</xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
    <xs:key name="version-code">
      <xs:selector xpath="version"/>
      <xs:field xpath="@code"/>
    </xs:key>
    <xs:keyref name="version-code-default" refer="version-code">
      <xs:selector xpath="."/>
      <xs:field xpath="@defaultVersion"/>
    </xs:keyref>
    <xs:unique name="artifactPageExtension-value-unique">
      <xs:selector xpath="artifactPageExtension"/>
      <xs:field xpath="@value"/>
    </xs:unique>
    <xs:unique name="artifact-key-unique">
      <xs:selector xpath="artifact"/>
      <xs:field xpath="@key"/>
    </xs:unique>
    <xs:unique name="artifact-name-unique">
      <xs:selector xpath="artifact"/>
      <xs:field xpath="@name"/>
    </xs:unique>
    <xs:unique name="artifact-id-unique">
      <xs:selector xpath="artifact"/>
      <xs:field xpath="@id"/>
    </xs:unique>
    <xs:unique name="page-key-unique">
      <xs:selector xpath="page"/>
      <xs:field xpath="@key"/>
    </xs:unique>
    <xs:unique name="page-name-unique">
      <xs:selector xpath="page"/>
      <xs:field xpath="@name"/>
    </xs:unique>
    <xs:unique name="page-url-unique">
      <xs:selector xpath="page"/>
      <xs:field xpath="@url"/>
    </xs:unique>
    <xs:unique name="page-otherpage-url-unique">
      <xs:selector xpath="page/otherpage"/>
      <xs:field xpath="@url"/>
    </xs:unique>
  </xs:element>
  <xs:simpleType name="website">
    <xs:restriction base="xs:anyURI">
      <xs:pattern value="http(s)?://(\S)+[^/]"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Name">
    <xs:restriction base="xs:string">
      <xs:pattern value="[^\s]+([\s][^\s]+)*"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="NonEmptyString">
    <xs:restriction base="xs:string">
      <xs:pattern value="[^\s]+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== HL7/JIRA-Spec-Artifacts/xml/OTHER-dss.xml
<?xml version="1.1" encoding="UTF-8"?>
<specification defaultWorkgroup="cds" defaultVersion="1.2" url="http://www.hl7.org/implement/standards/product_brief.cfm?product_id=334" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/specification.xsd">
  <version code="1.2" deprecated="false"/>
  <version code="1.1" deprecated="false"/>
  <page name="1.0 - Introduction" key="1_intro"/>
  <page name="1.1 - S and I Framework HeD Initiative" key="1_1_hed_initiative"/>
  <page name="1.2 - Purpose" key="1_2_purpose"/>
  <page name="1.3 - Approach" key="1_3_approach"/>
  <page name="1.4 - Intended Audience" key="1_4_audience"/>
  <page name="1.5 - Conventions and Acronyms Used in this Guide" key="1_5_conventions"/>
  <page name="1.6 - Acronyms" key="1_6_acronyms"/>
  <page name="2.0 - Implementation Approach" key="2_0_impl_approach"/>
  <page name="2.1 - Pre-Conditions" key="2_1_pre_conditions"/>
  <page name="2.2 - Implementation Resources" key="2_2_impl_resources"/>
  <page name="2.3 - Service Interaction Framework" key="2_3_svc_ineract_xwork"/>
  <page name="2.4 - Content Payload Definition" key="2_4_cnt_payload_def"/>
  <page name="2.5 - Clinical Data Representation" key="2_5_data_rep"/>
  <page name="2.6 - Specification of Knowledge Module Meta-Data" key="2_6_meta_data"/>
  <page name="2.7 - Example Implementation" key="2_7_impl_example"/>
  <page name="Appendix A - Acronyms" key="app_a_acronyms"/>
  <page name="Appendix B - Glossary of Terms" key="app_b_glossary"/>
</specification>

=== HL7/JIRA-Spec-Artifacts/xml/CDA-haiaultc.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/specification.xsd" defaultVersion="1.0.0" defaultWorkgroup="pher" url="https://www.hl7.org/documentcenter/public/ballots/2024JAN/downloads/CDAR2_IG_HAI_AU_LTCF_E1_D1_2024JAN.zip" >
    <version code="0.1.0" deprecated="false"/>
    <version code="1.0.0" deprecated="false"/>
    <page key="NA" name="(NA)"/>
    <page key="many" name="(many)"/>
    <page key="usecases" name="Use Cases"/>
    <page key="narratives" name="Narrative Guidance"/>
    <page key="templates" name="Templates"/>
    <page key="figures-examples" name="Figures and Examples"/>
    <page key="valuesets" name="Value sets"/>
    <page key="samplefiles" name="Sample Files"/>
    <page key="schematron" name="Schematron Validation Files"/>
</specification>

=== HL7/JIRA-Spec-Artifacts/xml/CDA-nhcs.xml
<?xml version="1.1" encoding="UTF-8"?>
<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="schemas/specification.xsd" defaultVersion="1.3.0"
	defaultWorkgroup="pher" url="http://www.hl7.org/implement/standards/product_brief.cfm?product_id=385">
	<!--<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="schemas/specification.xsd" defaultVersion="STU3"
 defaultWorkgroup="ph">-->
	<version code="1.3.0" url="http://www.hl7.org/dstucomments/showdetail.cfm?dstuid=282" deprecated="false"/>
	<version code="1.2.0" url="http://www.hl7.org/dstucomments/showdetail.cfm?dstuid=267" deprecated="true"/>
	<version code="1.1.2" url="http://www.hl7.org/dstucomments/showdetail.cfm?dstuid=192" deprecated="true"/>
	<version code="1.1.1" url="http://www.hl7.org/dstucomments/ex_showdetail.cfm?dstuid=179" deprecated="true"/>
	<version code="1.1.0" url="http://www.hl7.org/dstucomments/ex_showdetail.cfm?dstuid=136" deprecated="true"/>
		<page key="NA" name="(NA)"/>
		<page key="many" name="(many)"/>
		<page key="usecases" name="Use Cases"/>
		<page key="narratives" name="Narrative Guidance"/>
		<page key="templates" name="Templates"/>
		<page key="figures-examples" name="Figures and Examples"/>
		<page key="valuesets" name="Value sets"/>
		<page key="samplefiles" name="Sample Files"/>
		<page key="schematron" name="Schematron Validation Files"/>
	</specification>

=== HL7/JIRA-Spec-Artifacts/xml/V2-dar.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification defaultWorkgroup="pher" defaultVersion="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/specification.xsd">
  <version code="1.0"/>
  <artifact name="ORU^R01 Profile" key="ORUprofile" id="ORU/DAR"/>
  <artifact name="ACK^R01 Profile" key="ACKprofile" id="ACK/DAR"/>
  <artifact name="MSH_EHDI01 Profile" key="MSH_EHDI01" id="MSH/EHDI01"/>
  <artifact name="MSH_EHDI02 Profile" key="MSH_EHDI02" id="MSH/EHDI02"/>
  <artifact name="PID_EHDI01 Profile" key="PID_EHDI01" id="PID/EHDI01"/>
  <artifact name="NK1_EHDI01 Profile" key="NK1_EHDI01" id="NK1/EHDI01"/>
  <artifact name="PV1_EHDI01 Profile" key="PV1_EHDI01" id="PV1/EHDI01"/>
  <artifact name="OBR_EHDI01 Profile" key="OBR_EHDI01" id="OBR/EHDI01"/>
  <artifact name="OBX_EHDI01 Profile" key="OBX_EHDI01" id="OBX/EHDI01"/>
  <artifact name="MSA_EHDI01 Profile" key="MSA_EHDI01" id="MSA/EHDI01"/>
  <artifact name="ERR_EHDI01 Profile" key="ERR_EHDI01" id="ERR/EHDI01"/>
  <artifact name="Value Sets" key="valuesets" id="VALUESET/EHDI"/>
  <artifact name="Data Type Flavors" key="datatypeflavors" id="DATATYPES/EHDI"/>
  <page name="Introduction" key="intro"/>
  <page name="Use Cases" key="usecases"/>
  <page name="Other" key="other"/>
</specification>

=== HL7/JIRA-Spec-Artifacts/xml/CDA-core.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- This data is just for testing purposes and is not complete -->
<specification defaultWorkgroup="sd" defaultVersion="R2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/specification.xsd">
  <version code="R1"/>
  <version code="R2"/>
  <version code="R2.1"/>
  <artifact name="SomeClass" key="someclass" id="1.2.3"/>
  <artifact name="SomeOtherClass6" key="someotherclass" id="0.1.2"/>
  <page name="(NA)" key="NA"/>
  <page name="(many)" key="many"/>
  <page name="(methodology)" key="methodology"/>
  <page name="(profiles)" key="profiles"/>
  <page name="Intro" key="intro"/>
</specification>

=== HL7/JIRA-Spec-Artifacts/xml/OTHER-sb-pft.xml
<?xml version="1.1" encoding="UTF-8"?>
<specification defaultWorkgroup="pc" defaultVersion="1.0" 
    url="http://www.hl7.org/documentcenter/public/ballots/2025MAY/downloads/HL7_DAM_SB-PFT_E1_I1_2025MAY.zip" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="../schemas/specification.xsd">
    <version code="1.0" deprecated="false"/>
    <page name="Background" key="Background"/>
    <page name="Purpose" key="Purpose"/>
    <page name="Acknowledgements" key="Acknowledgements"/>
    <page name="Use Cases" key="UseCases"/>
    <page name="Use Cases Activities" key="UseCasesActivities"/>
    <page name="Activity Process Flows" key="ActivityProcessFlows"/>
    <page name="Interactions" key="Interactions"/>
    <page name="Information Viewpoint" key="InformationViewpoint"/>
</specification>

=== HL7/JIRA-Spec-Artifacts/xml/CDA-hai.xml
<?xml version="1.1" encoding="UTF-8"?>
<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="../schemas/specification.xsd" defaultVersion="4.4.1"
defaultWorkgroup="sd" url="http://www.hl7.org/implement/standards/product_brief.cfm?product_id=570">
<version code="4.4.1" deprecated="false"/>
<version code="4.4.1-snapshot" deprecated="true"/>
<version code="4.4.0" deprecated="false"/>
<version code="4.3.0" deprecated="false"/>
<version code="4.2.2" deprecated="false"/>
<version code="4.2.1" deprecated="true"/>
<version code="4.2.0" deprecated="true"/>
<version code="4.1.0" deprecated="true"/>
<version code="3.0.0" deprecated="true"/>
<version code="3.4.0" deprecated="true"/>
<version code="3.3.0" deprecated="false"/>
<version code="2.1.0" deprecated="true"/>
<page key="NA" name="(NA)"/>
<page key="many" name="(many)"/>
<page key="usecases" name="Use Cases"/>
<page key="narratives" name="Narrative Guidance"/>
<page key="templates" name="Templates"/>
<page key="figures-examples" name="Figures and Examples"/>
<page key="valuesets" name="Value sets"/>
<page key="samplefiles" name="Sample Files"/>
<page key="schematron" name="Schematron Validation Files"/>
</specification>

=== HL7/JIRA-Spec-Artifacts/xml/FHIR-cql.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification gitUrl="https://github.com/HL7/cql" url="http://cql.hl7.org" ciUrl="http://build.fhir.org/ig/HL7/cql" defaultWorkgroup="cds" defaultVersion="1.4" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/specification.xsd">
  <version code="1.0" url="http://www.hl7.org/documentcenter/public/standards/dstu/HL7_CQLANG_R1_DSTU_2015MAY.zip" deprecated="true"/>
  <version code="1.1" url="http://www.hl7.org/documentcenter/public/standards/dstu/HL7_CQL_SPEC_R1_DSTUR1dot1_2016JUL.zip" deprecated="true"/>
  <version code="1.2" url="http://cql.hl7.org/STU2/index.html" deprecated="true"/>
  <version code="1.3" url="http://cql.hl7.org/STU3/index.html" deprecated="true"/>
  <version code="1.4" url="http://cql.hl7.org/STU4/index.html"/>
  <version code="1.5"/>
  <page name="(NA)" key="NA"/>
  <page name="Index" key="index"/>
  <page name="Documentation" key="documentation"/>
  <page name="Grammar" key="grammar"/>
  <page name="ELM" key="elm"/>
  <page name="Examples" key="examples"/>
  <page name="Tests" key="tests"/>
  <page name="Downloads" key="downloads"/>
  <page name="History" key="history"/>
  <page name="Introduction" key="introduction"/>
  <page name="Authors Guide" key="authorsguide"/>
  <page name="Developers Guide" key="developersguide"/>
  <page name="Logical Specification" key="logicalspecification"/>
  <page name="Language Semantics" key="languagesemantics"/>
  <page name="Translation Semantics" key="translationsemantics"/>
  <page name="Physical Representation" key="physicalrepresentation"/>
  <page name="Appendix A - Syntax" key="appendixa"/>
  <page name="Appendix B - Reference" key="appendixb"/>
  <page name="Appendix C - Implementations" key="appendixc"/>
  <page name="Appendix D - References" key="appendixd"/>
  <page name="Appendix E - Acronyms" key="appendixe"/>
  <page name="Appendix F - Glossary" key="appendixf"/>
  <page name="Appendix G - Conventions" key="appendixg"/>
  <page name="Appendix H - Interval Examples" key="appendixh"/>
  <page name="Appendix I - FHIRPath Translation" key="appendixi"/>
  <page name="Appendix J - List of Tables" key="appendixj"/>
  <page name="Appendix K - List of Figures" key="appendixk"/> 
</specification>
