=== HL7/JIRA-Spec-Artifacts/schemas/specification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  When this schema is changed, the following code must be updated to align:
  - Scriptrunner REST Endpoints: uploadBallotSpreadsheet
  - BALDEF Workflow (2 classes x 2 locations)
  - SPEC Workflow (1 class)
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="workgroups.xsd"/>
  <xs:element name="specification">
    <xs:annotation>
      <xs:documentation>All content related to a single HL7 specification.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="version" minOccurs="1" maxOccurs="unbounded">
          <xs:annotation>
            <xs:documentation>Indicates an official major published release version.  (Technical correction releases are not tracked.)  Used to identify list of allowed versions when tracking version issue is raised in and fixed in.</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:attribute name="code" type="xs:NMTOKEN" use="required">
              <xs:annotation>
                <xs:documentation>The code to display for the version</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="url" type="website" use="optional">
              <xs:annotation>
                <xs:documentation>The persistant URL associated with this version of the specification.  Used in URL validation.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="deprecated" type="xs:boolean" default="false">
              <xs:annotation>
                <xs:documentation>If true, indicates that the version will not be available for selection as a 'reported version' when submitting new issues.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
        <xs:element name="artifactPageExtension" minOccurs="0" maxOccurs="unbounded">
          <xs:annotation>
            <xs:documentation>Indicates suffixes that might be associated with pages generated for artifacts.  Used for checking/populating artifacts based on URLs entered for the tracker</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:attribute name="value" type="xs:NMTOKEN" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="artifact" minOccurs="0" maxOccurs="unbounded">
          <xs:annotation>
            <xs:documentation>A formal artifact that can be referenced as part of feedback on a specification</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="otherArtifact" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                  <xs:documentation>Indicates additional artifacts whose issues should be reported under the parent artifact</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:attribute name="id" type="NonEmptyString" use="required">
                    <xs:annotation>
                      <xs:documentation>The formal identifier for the artifact whose issues are to be reported under the parent artifact</xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="key" type="xs:NMTOKEN" use="required">
              <xs:annotation>
                <xs:documentation>The key used inside Jira to identify the artifact.  This key must not be renamed and cannot be removed if it appears in any tracker item.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="name" type="Name" use="required">
              <xs:annotation>
                <xs:documentation>The name to display to users for the artifact.  This can change if the artifact is renamed</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="id" type="NonEmptyString" use="optional">
              <xs:annotation>
                <xs:documentation>The formal identifier associated with the artifact (if there is one).  OID for CDA templates, ResourceType/id for FHIR, etc.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="workgroup" type="WorkGroup" use="optional">
              <xs:annotation>
                <xs:documentation>The work group typically responsible for issues relating to this artifact</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="deprecated" type="xs:boolean" default="false">
              <xs:annotation>
                <xs:documentation>If true, indicates that the artifact can no longer be associated with newly raised issues, but it can still appear on old issues and be used in search</xs:documentation>
              </xs:annotation>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
        <xs:element name="page" maxOccurs="unbounded">
          <xs:annotation>
            <xs:documentation>Indicates a documentation page that's not tightly associated with an artifact</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="otherpage" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                  <xs:documentation>Additional page URLs that should be treated as part of this page for categorization purposes (used to infer/validate pages based on URL)</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:attribute name="url" type="xs:NMTOKEN" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="key" type="xs:NMTOKEN" use="required">
              <xs:annotation>
                <xs:documentation>The key used inside Jira to identify the page  This key must not be renamed and cannot be removed if it appears in any tracker item.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="name" type="Name" use="required">
              <xs:annotation>
                <xs:documentation>The name to display to users for the page.  This can change if the page is renamed</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="workgroup" type="WorkGroup" use="optional">
              <xs:annotation>
                <xs:documentation>The work group typically responsible for issues relating to this page</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="deprecated" type="xs:boolean" default="false">
              <xs:annotation>
                <xs:documentation>If true, indicates that the page can no longer be associated with newly raised issues, but it can still appear on old issues and be used in search</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="url" type="xs:NMTOKEN" use="optional">
              <xs:annotation>
                <xs:documentation>The primary url associated with this page (this may initially be the same as the key, but will change if the url changes)</xs:documentation>
              </xs:annotation>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="url" type="website" use="optional">
        <xs:annotation>
          <xs:documentation>The official URL for this specification.  Used when validating URLs</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="ciUrl" type="website" use="optional">
        <xs:annotation>
          <xs:documentation>The continuous integration build URL for this specification.  Used when validating URLs</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="ballotUrl" type="website" use="optional">
        <xs:annotation>
          <xs:documentation>The URL for the current/most recent ballot of this specification.  Used when validating URLs</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="gitUrl" type="website" use="optional">
        <xs:annotation>
          <xs:documentation>The base URL for the repository in which the source material for this specificaiton is maintained.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="defaultWorkgroup" type="WorkGroup" use="optional">
        <xs:annotation>
          <xs:documentation>The work group typically associated with issues raised against this specification if a more specific work group isn't determined based on pages or artifacts</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="defaultVersion" type="xs:NMTOKEN" use="required">
        <xs:annotation>
          <xs:documentation>The version to identify as the 'raised' version for an issue if not overridden by the submitter</xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
    <xs:key name="version-code">
      <xs:selector xpath="version"/>
      <xs:field xpath="@code"/>
    </xs:key>
    <xs:keyref name="version-code-default" refer="version-code">
      <xs:selector xpath="."/>
      <xs:field xpath="@defaultVersion"/>
    </xs:keyref>
    <xs:unique name="artifactPageExtension-value-unique">
      <xs:selector xpath="artifactPageExtension"/>
      <xs:field xpath="@value"/>
    </xs:unique>
    <xs:unique name="artifact-key-unique">
      <xs:selector xpath="artifact"/>
      <xs:field xpath="@key"/>
    </xs:unique>
    <xs:unique name="artifact-name-unique">
      <xs:selector xpath="artifact"/>
      <xs:field xpath="@name"/>
    </xs:unique>
    <xs:unique name="artifact-id-unique">
      <xs:selector xpath="artifact"/>
      <xs:field xpath="@id"/>
    </xs:unique>
    <xs:unique name="page-key-unique">
      <xs:selector xpath="page"/>
      <xs:field xpath="@key"/>
    </xs:unique>
    <xs:unique name="page-name-unique">
      <xs:selector xpath="page"/>
      <xs:field xpath="@name"/>
    </xs:unique>
    <xs:unique name="page-url-unique">
      <xs:selector xpath="page"/>
      <xs:field xpath="@url"/>
    </xs:unique>
    <xs:unique name="page-otherpage-url-unique">
      <xs:selector xpath="page/otherpage"/>
      <xs:field xpath="@url"/>
    </xs:unique>
  </xs:element>
  <xs:simpleType name="website">
    <xs:restriction base="xs:anyURI">
      <xs:pattern value="http(s)?://(\S)+[^/]"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Name">
    <xs:restriction base="xs:string">
      <xs:pattern value="[^\s]+([\s][^\s]+)*"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="NonEmptyString">
    <xs:restriction base="xs:string">
      <xs:pattern value="[^\s]+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== HL7/JIRA-Spec-Artifacts/xml/FHIR-us-pro.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification gitUrl="https://github.com/HL7/patient-reported-outcomes" url="http://hl7.org/fhir/us/patient-reported-outcomes" ciUrl="http://build.fhir.org/ig/HL7/patient-reported-outcomes" defaultWorkgroup="pharm" defaultVersion="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/specification.xsd">
  <version code="0.1"/>
  <artifactPageExtension value="-definitions"/>
  <artifactPageExtension value="-examples"/>
  <artifactPageExtension value="-mappings"/>
  <artifact name="Questionnaire" key="Questionnaire" deprecated="true"/>
  <page name="(NA)" key="NA"/>
  <page name="(many)" key="many"/>
  <page name="(profiles)" key="profiles"/>
  <page name="index" key="index"/>
  <page name="documentation" key="documentation" url="documentation" deprecated="true"/>
  <page name="downloads" key="downloads" url="downloads" deprecated="true"/>
  <page name="overview" key="overview" url="overview" deprecated="true"/>
  <page name="terminologies" key="terminologies" url="terminologies" deprecated="true"/>
</specification>

=== HL7/JIRA-Spec-Artifacts/xml/FHIR-ipa.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" gitUrl="https://github.com/HL7/fhir-ipa"
               url="http://hl7.org/fhir/uv/ipa"
               ciUrl="https://build.fhir.org/ig/HL7/fhir-ipa"
               defaultWorkgroup="pc"
               defaultVersion="1.0.0"
               xsi:noNamespaceSchemaLocation="../schemas/specification.xsd">
               <!-- ballotUrl="http://hl7.org/fhir/uv/ips/2019Sep"> -->
   <version code="current" url="https://build.fhir.org/ig/HL7/fhir-ipa"/>
   <version code="1.0.0" url="http://hl7.org/fhir/uv/ipa/STU1"/>
   <version code="0.1"/>
   <artifactPageExtension value="-definitions"/>
   <artifactPageExtension value="-examples"/>
   <artifactPageExtension value="-mappings"/>
   <artifact id="CapabilityStatement/ipa-server" key="CapabilityStatement-ipa-server" name="CapabilityStatement - International Patient Access"/>
   <artifact id="OperationDefinition/docref" key="OperationDefinition-docref" name="IPA Fetch DocumentReference"/>
   <artifact id="StructureDefinition/ipa-allergyintolerance" key="StructureDefinition-ipa-allergyintolerance" name="IPA-AllergyIntolerance"/>
   <artifact id="StructureDefinition/ipa-condition" key="StructureDefinition-ipa-condition" name="IPA-Condition"/>
   <artifact id="StructureDefinition/ipa-documentreference" key="StructureDefinition-ipa-documentreference" name="IPA-DocumentReference"/>
   <artifact id="StructureDefinition/ipa-immunization" key="StructureDefinition-ipa-immunization" name="IPA-Immunization"/>
   <artifact id="StructureDefinition/ipa-medication" key="StructureDefinition-ipa-medication" name="IPA-Medication"/>
   <artifact id="StructureDefinition/ipa-medicationrequest" key="StructureDefinition-ipa-medicationrequest" name="IPA-MedicationRequest"/>
   <artifact id="StructureDefinition/ipa-medicationstatement" key="StructureDefinition-ipa-medicationstatement" name="IPA-MedicationStatement"/>
   <artifact id="StructureDefinition/ipa-observation" key="StructureDefinition-ipa-observation" name="IPA-Observation"/>
   <artifact id="StructureDefinition/ipa-patient" key="StructureDefinition-ipa-patient" name="IPA-Patient"/>
   <artifact id="StructureDefinition/ipa-practitioner" key="StructureDefinition-ipa-practitioner" name="IPA-Practitioner"/>
   <artifact id="StructureDefinition/ipa-practitionerrole" key="StructureDefinition-ipa-practitionerrole" name="IPA-PractitionerRole"/>
   <page name="(NA)" key="NA"/>
   <page name="(many)" key="many"/>
   <page name="Table of Contents" key="toc"/>
   <page name="International Patient Access Implementation Guide" key="index"/>
   <page key="artifacts" name="Artifact List"/>
   <page key="conformance" name="Conforming to this specification"/>
   <page key="downloads" name="Downloads"/>
   <page key="fetching" name="Finding / Retrieving information about the patient"/>
   <page key="access" name="Gaining Access to a patient record"/>
   <page key="ipa-server" name="IPA Server Rules"/>
   <page key="internationalization" name="Internationalization Issues"/>
</specification>

=== HL7/JIRA-Spec-Artifacts/xml/CDA-hai-two.xml
<?xml version="1.1" encoding="UTF-8"?>
	<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="schemas/specification.xsd" defaultVersion="2.1.0"
		defaultWorkgroup="sd" url="http://www.hl7.org/implement/standards/product_brief.cfm?product_id=426">
		<!--<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="schemas/specification.xsd" defaultVersion="STU1"
 defaultWorkgroup="sd">-->
		<version url="http://www.hl7.org/implement/standards/product_brief.cfm?product_id=419" deprecated="false" code="2.1.0"/>
		<page key="NA" name="(NA)"/>
		<page key="many" name="(many)"/>
		<page key="usecases" name="Use Cases"/>
		<page key="narratives" name="Narrative Guidance"/>
		<page key="templates" name="Templates"/>
		<page key="figures-examples" name="Figures and Examples"/>
		<page key="valuesets" name="Value sets"/>
		<page key="samplefiles" name="Sample Files"/>
		<page key="schematron" name="Schematron Validation Files"/>
	</specification>

=== HL7/JIRA-Spec-Artifacts/xml/FHIR-us-crn.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification gitUrl="https://github.com/HL7/coordinated-registry-network" url="http://hl7.org/fhir/us/womens-health-registries" ciUrl="http://build.fhir.org/ig/HL7/coordinated-registry-network" defaultWorkgroup="brr" defaultVersion="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/specification.xsd">
  <version code="0.1"/>
  <artifactPageExtension value="-definitions"/>
  <artifactPageExtension value="-examples"/>
  <artifactPageExtension value="-mappings"/>
  <artifact name="Device" key="Device" deprecated="true"/>
  <artifact name="Procedure" key="Procedure" deprecated="true"/>
  <page name="(NA)" key="NA"/>
  <page name="(many)" key="many"/>
  <page name="(profiles)" key="profiles"/>
  <page name="index" key="index"/>
  <page name="overview" key="overview" url="overview" deprecated="true"/>
  <page name="schemas-schematrons" key="schemas-schematrons" url="schemas-schematrons" deprecated="true"/>
</specification>

=== HL7/JIRA-Spec-Artifacts/xml/OTHER-rccmh.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification defaultWorkgroup="mh" defaultVersion="1.0-ballot" url="http://www.hl7.org/documentcenter/public/ballots/2025MAY/downloads/HL7_RCC-MH_E1_S1_2025MAY.pdf" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/specification.xsd">
  <version code="1.0-ballot" deprecated="false"/>
  <page name="Foreward" key="foreword"/>
  <page name="Introduction" key="introduction"/>
  <page name="Scope" key="scope"/>
  <page name="Normative references" key="normref"/>
  <page name="Terms and definitions" key="termsdef"/>
  <page name="Abbreviations" key="abbrev"/>
  <page name="RCC-MH care locations and evolution" key="careloc"/>
  <page name="RCC-MH relevant care delivery modes and use cases" key="caredelivery"/>
  <page name="RCC-MH challenges and gaps" key="gaps"/>
  <page name="RCC-MH recommendations" key="recommendations"/>
  <page name="Conclusions and path forward" key="conclusions"/>
  <page name="Annex A" key="annexa"/>
  <page name="Annex B" key="annexb"/>
  <page name="Annex C" key="annexc"/>
  <page name="Annex D" key="annexd"/>
  <page name="Annex E" key="annexe"/>
  <page name="Annex F" key="annexf"/>
  <page name="Annex G" key="annexg"/>
  <page name="Annex H" key="annexh"/>
  <page name="Annex I" key="annexi"/>
  <page name="Annex J" key="annexj"/>
  <page name="Annex K" key="annexk"/>
  <page name="Annex L" key="annexl"/>
  <page name="Bibliography" key="bibliography"/>
</specification>

=== HL7/JIRA-Spec-Artifacts/xml/OTHER-stmed-profile.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification defaultWorkgroup="pharm" defaultVersion="1.0" url="http://www.hl7.org/documentcenter/public/ballots/2021MAY/downloads/HL7_STD_MED_PROFILE_R1_I1_2021MAY.pdf" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/specification.xsd">
  <version code="1.0" deprecated="false"/>
  <page name="Purpose" key="purpose"/>
  <page name="Background and Significance" key="background"/>
  <page name="Joint NCPDP/HL7 Project Effort" key="joint_effort"/>
  <page name="NCPDP/HL7 Gap Analysis" key="gap_analysis"/>
  <page name="Analysis of Information" key="info_analysis"/>
  <page name="Recommendation and Conclusion" key="recomm"/>
  <page name="References" key="refs"/>
  <page name="Appendix" key="append"/>
</specification>

=== HL7/JIRA-Spec-Artifacts/xml/V2-lri.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification defaultWorkgroup="oo" defaultVersion="2.5.1_E5" url="https://www.hl7.org/implement/standards/product_brief.cfm?product_id=279" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/specification.xsd">
  <version code="2.5.1_E5" deprecated="false"/> 
  <version code="2.5.1_E6_2026May" deprecated="false"/> 
  <version code="V251_IG_LRI_E1_STU5_2024Jan" deprecated="true"/>   
  <version code="2.5.1_R1_STU4" deprecated="true"/> 
  <version code="2.5.1_R1_2022JUL-PR" deprecated="true"/>
  <version code="2.5.1_R1_2021SEP" deprecated="true"/>
  <version code="2.5.1_R1_STU3" deprecated="true"/>
  <version code="2.5.1_R1_DSTU2" deprecated="true"/>
  <version code="2.5.1_R1_DSTU1" deprecated="true"/>
  <artifact name="ORU^R01 Profile" key="ORUprofile" id="ORU/LRI"/>
  <artifact name="ACK^R01 Accept Profile" key="ACKacceptprofile" id="ACK/LRIaccept"/>
  <artifact name="ACK^R01 Application Profile" key="ACKapplicationprofile" id="ACK/LRIapplication"/>
  <artifact name="Batch Protocol Profile" key="Batchprofile" id="Batch/LRI"/>
  <artifact name="MSH_LRI Profile" key="MSH_LRI" id="MSH/LRI"/>
  <artifact name="SFT_LRI Profile" key="SFT_LRI" id="SFT/LRI"/>
  <artifact name="MSA_LRI Profile" key="MSA_LRI" id="MSA/LRI"/>
  <artifact name="ERR_LRI Profile" key="ERR_LRI" id="ERR/LRI"/>
  <artifact name="PID_LRI Profile" key="PID_LRI" id="PID/LRI"/>
  <artifact name="PRT_LRI Profile" key="PRT_LRI" id="PRT/LRI"/>
  <artifact name="NK1_LRI Profile" key="NK1_LRI" id="NK1/LRI"/>
  <artifact name="PV1_LRI Profile" key="PV1_LRI" id="PV1/LRI"/>
  <artifact name="ORC_LRI Profile" key="ORC_LRI" id="ORC/LRI"/>
  <artifact name="OBR_LRI Profile" key="OBR_LRI" id="OBR/LRI"/>
  <artifact name="TQ1_LRI Profile" key="TQ1_LRI" id="TQ1/LRI"/>
  <artifact name="OBX_LRI Profile" key="OBX_LRI" id="OBX/LRI"/>
  <artifact name="SPM_LRI Profile" key="SPM_LRI" id="SPM/LRI"/>
  <artifact name="NTE_LRI Profile" key="NTE_LRI" id="NTE/LRI"/>
  <artifact name="FHS_LRI Profile" key="FHS_LRI" id="FHS/LRI"/>
  <artifact name="FTS_LRI Profile" key="FTS_LRI" id="FTS/LRI"/>
  <artifact name="BHS_LRI Profile" key="BHS_LRI" id="BHS/LRI"/>
  <artifact name="BTS_LRI Profile" key="BTS_LRI" id="BTS/LRI"/>
  <artifact name="Data Type Flavors" key="datatypeflavors" id="DATATYPES/CCHD"/>
  <page name="Introduction" key="intro"/>
  <page name="Laboratory Results Use Case" key="results"/>
  <page name="Public Health Reporting Use Case" key="publichealth"/>
  <page name="Newborn Dried Blood Spot Use Case" key="ndbs"/>
  <page name="Clinical Genomics Use Case" key="genomics"/>
  <page name="Pandemic Response (reporting to US HHS) Use Case" key="pandemicresponse"/>
  <page name="Conformance" key="conformance"/>
  <page name="Acknowledgments" key="acknowledgements"/>
  <page name="Code Systems" key="codesystems"/>
  <page name="Cancer Registry Pathology Reporting" key="naaccr"/>
  <page name="Message Development Resources" key="resources"/>
  <page name="Additional Implementation Guidance - Culture" key="cultureguidance"/>
  <page name="Additional Implementation Guidance - Other" key="otherguidance"/>
  <page name="Clinical Genomics Code Systems" key="cgcodesystems"/>
  <page name="NDBS LOINC Requirements" key="ndbsloinc"/>
  <page name="Glossary" key="glossary"/>
  <page name="Other" key="other"/>
  <page key="TBD" name="TBD"/>
  <page name="Value Sets" key="valuesets"/>
</specification>

=== HL7/JIRA-Spec-Artifacts/xml/V2-elr.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification defaultWorkgroup="oo" defaultVersion="1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/specification.xsd">
  <version code="1.1"/>
  <artifact name="ORU^R01 Profile" key="ORUprofile" id="ORU/ELR"/>
  <artifact name="ACK^R01 Profile" key="ACKprofile" id="ACK/ELR"/>
  <artifact name="Batch Protocol Profile" key="Batchprofile" id="Batch/ELR"/>
  <artifact name="MSH_ELR Profile" key="MSH_ELR" id="MSH/ELR"/>
  <artifact name="SFT_ELR Profile" key="SFT_ELR" id="SFT/ELR"/>
  <artifact name="MSA_ELR Profile" key="MSA_ELR" id="MSA/ELR"/>
  <artifact name="ERR_ELR Profile" key="ERR_ELR" id="ERR/ELR"/>
  <artifact name="PID_ELR Profile" key="PID_ELR" id="PID/ELR"/>
  <artifact name="NK1_ELR Profile" key="NK1_ELR" id="NK1/ELR"/>
  <artifact name="PV1_ELR Profile" key="PV1_ELR" id="PV1/ELR"/>
  <artifact name="ORC_ELR Profile" key="ORC_ELR" id="ORC/ELR"/>
  <artifact name="OBR_ELR Profile" key="OBR_ELR" id="OBR/ELR"/>
  <artifact name="TQ1_ELR Profile" key="TQ1_ELR" id="TQ1/ELR"/>
  <artifact name="OBX_ELR Profile" key="OBX_ELR" id="OBX/ELR"/>
  <artifact name="SPM_ELR Profile" key="SPM_ELR" id="SPM/ELR"/>
  <artifact name="NTE_ELR Profile" key="NTE_ELR" id="NTE/ELR"/>
  <artifact name="FHS_ELR Profile" key="FHS_ELR" id="FHS/ELR"/>
  <artifact name="FTS_ELR Profile" key="FTS_ELR" id="FTS/ELR"/>
  <artifact name="BHS_ELR Profile" key="BHS_ELR" id="BHS/ELR"/>
  <artifact name="BTS_ELR Profile" key="BTS_ELR" id="BTS/ELR"/>
  <artifact name="Data Type Flavors" key="datatypeflavors" id="DATATYPES/CCHD"/>
  <page name="Introduction" key="intro"/>
  <page name="PH Component" key="phcomponent"/>
  <page name="Purpose" key="purpose"/>
  <page name="Audience" key="audience"/>
  <page name="Requisite Knowledge" key="reqknowledge"/>
  <page name="Organization of the Guide" key="organization"/>
  <page name="Scope" key="scope"/>
  <page name="Ambulatory Care Use Case" key="ambulatory"/>
  <page name="User Story" key="userstory"/>
  <page name="Assumptions" key="assumptions"/>
  <page name="Sequence Diagram" key="sequencediagram"/>
  <page name="Key Technical Decisions" key="techdecisions"/>
  <page name="Referenced Profiles" key="profiles"/>
  <page name="Actors" key="actors"/>
  <page name="Conformance to the Guide" key="conformance"/>
  <page name="Code Sysems and Value Sets" key="codes"/>
  <page name="Message Development Resources" key="resources"/>
  <page name="Additional Implementation Guidance - Culture" key="cultureguidance"/>
  <page name="Additional Implementation Guidance - Other" key="otherguidance"/>
  <page name="Additional Implementation Guidance - Public Health Reporting" key="phguidance"/>
  <page name="Appendix A (Glossary)" key="glossary"/>
  <page name="Appendix B (PH Resources)" key="phresources"/>
  <page name="Appendix C (Version Changes)" key="versionchanges"/>
  <page name="Appendix D (Release 1.0 to 1.1)" key="releasechanges"/>
  <page name="Other" key="other"/>
</specification>
