=== HL7/JIRA-Spec-Artifacts/schemas/specificationList.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:documentation>Validates files listing all specifications for a single product family</xs:documentation>
  </xs:annotation>
  <xs:element name="specifications">
    <xs:annotation>
      <xs:documentation>A grouper for all specifications for the family</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="specification" maxOccurs="unbounded">
          <xs:annotation>
            <xs:documentation>A single specification (core spec, implementation guide, etc.) that Jira feedback can be raised about</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:attribute name="key" use="required">
              <xs:annotation>
                <xs:documentation>The internal key used within Jira trackers.  This should never change or be removed</xs:documentation>
              </xs:annotation>
              <xs:simpleType>
                <xs:restriction base="xs:NMTOKEN">
                  <xs:pattern value="[a-z0-9\-]+"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="name" use="required">
              <xs:annotation>
                <xs:documentation>The name to display when a user is looking at the tracker or selecting a specification for searching.  This can change if the specification is renamed</xs:documentation>
              </xs:annotation>
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="[A-Z][^\s]+([\s][^\s]+)*"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="deprecated" type="xs:boolean" default="false">
              <xs:annotation>
                <xs:documentation>If true, indicates that new feedback cannot be submitted against the specification any longer, however existing trackers referencing the specification can still be searched and displayed.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
    <xs:unique name="spec-key-unique">
      <xs:selector xpath="specification"/>
      <xs:field xpath="@key"/>
    </xs:unique>
    <xs:unique name="spec-name-unique">
      <xs:selector xpath="specification"/>
      <xs:field xpath="@name"/>
    </xs:unique>
  </xs:element>
</xs:schema>

=== HL7/JIRA-Spec-Artifacts/xml/SPECS-V2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  - A list of all specifications associated with the V2 product family (and managed through the V2 specification tracker)
  - Sort order reflects the order specifications will appear in the drop-down
  - The primary (default) specification should have a key of 'core'
  -
  - WARNING: Don't *ever* change the key as you'll break old tracker specifications.  Leave the key the same and change the name only.
  -
  - Note: This list is currently incomplete/incorrect and is just for test purposes
  -->
<specifications xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/specificationList.xsd">
	<specification key="core" name="V2.x Message Specification"/>
	<specification key="vtwoplus" name="V2+ Message Specification"/>
	<specification key="conformance" name="V2 Conformance Methodology"/>
	<specification key="vtwostdqc" name="V2 Base Standard Quality Criteria"/>
	<specification key="vtwoigqc" name="V2 Implementation Guide Quality Criteria"/>
	<specification key="vtwotofhir" name="V2 to FHIR"/>
	<specification key="ss" name="Syndromic Surveillance (US)"/>
	<specification key="bafd" name="Birth and Fetal Death Reporting (US)" deprecated="true"/>
	<specification key="vrdr" name="Vital Records Death Reporting (US)" deprecated="true"/>
	<specification key="cchd" name="Critical Congenital Heart Defect - CCHD (US)"/>
	<specification key="ehdi" name="Early Hearing Detection and Intervention - EHDI (US)"/>
	<specification key="dar" name="Diagnostic Audiology Reporting - DAR (US)"/>
	<specification key="imm" name="Immunization Messaging (US)"/>
	<specification key="loi" name="Laboratory Orders (LOI) (US)"/>
	<specification key="lri" name="Laboratory Results Interface (LRI) (US)"/>
	<specification key="edos" name="Laboratory Test Compendium (eDOS) (US)"/>
	<specification key="edos-aoe" name="Laboratory Test Compendium Ask at Order Entry (eDOS - AOE) (US)"/>
	<specification key="labvaluesets" name="V2.5.1 Laboratory Value Sets (US)"/>
	<specification key="elr" name="Electronic Lab Reporting to Public Health (ELR) (US)"/>
	<specification key="vmr-cds" name="Implementing the Virtual Medical Record for Clinical Decision Support (vMR-CDS)" deprecated="true"/>
</specifications>
