=== HL7/JIRA-Spec-Artifacts/schemas/specification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  When this schema is changed, the following code must be updated to align:
  - Scriptrunner REST Endpoints: uploadBallotSpreadsheet
  - BALDEF Workflow (2 classes x 2 locations)
  - SPEC Workflow (1 class)
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="workgroups.xsd"/>
  <xs:element name="specification">
    <xs:annotation>
      <xs:documentation>All content related to a single HL7 specification.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="version" minOccurs="1" maxOccurs="unbounded">
          <xs:annotation>
            <xs:documentation>Indicates an official major published release version.  (Technical correction releases are not tracked.)  Used to identify list of allowed versions when tracking version issue is raised in and fixed in.</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:attribute name="code" type="xs:NMTOKEN" use="required">
              <xs:annotation>
                <xs:documentation>The code to display for the version</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="url" type="website" use="optional">
              <xs:annotation>
                <xs:documentation>The persistant URL associated with this version of the specification.  Used in URL validation.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="deprecated" type="xs:boolean" default="false">
              <xs:annotation>
                <xs:documentation>If true, indicates that the version will not be available for selection as a 'reported version' when submitting new issues.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
        <xs:element name="artifactPageExtension" minOccurs="0" maxOccurs="unbounded">
          <xs:annotation>
            <xs:documentation>Indicates suffixes that might be associated with pages generated for artifacts.  Used for checking/populating artifacts based on URLs entered for the tracker</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:attribute name="value" type="xs:NMTOKEN" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="artifact" minOccurs="0" maxOccurs="unbounded">
          <xs:annotation>
            <xs:documentation>A formal artifact that can be referenced as part of feedback on a specification</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="otherArtifact" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                  <xs:documentation>Indicates additional artifacts whose issues should be reported under the parent artifact</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:attribute name="id" type="NonEmptyString" use="required">
                    <xs:annotation>
                      <xs:documentation>The formal identifier for the artifact whose issues are to be reported under the parent artifact</xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="key" type="xs:NMTOKEN" use="required">
              <xs:annotation>
                <xs:documentation>The key used inside Jira to identify the artifact.  This key must not be renamed and cannot be removed if it appears in any tracker item.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="name" type="Name" use="required">
              <xs:annotation>
                <xs:documentation>The name to display to users for the artifact.  This can change if the artifact is renamed</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="id" type="NonEmptyString" use="optional">
              <xs:annotation>
                <xs:documentation>The formal identifier associated with the artifact (if there is one).  OID for CDA templates, ResourceType/id for FHIR, etc.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="workgroup" type="WorkGroup" use="optional">
              <xs:annotation>
                <xs:documentation>The work group typically responsible for issues relating to this artifact</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="deprecated" type="xs:boolean" default="false">
              <xs:annotation>
                <xs:documentation>If true, indicates that the artifact can no longer be associated with newly raised issues, but it can still appear on old issues and be used in search</xs:documentation>
              </xs:annotation>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
        <xs:element name="page" maxOccurs="unbounded">
          <xs:annotation>
            <xs:documentation>Indicates a documentation page that's not tightly associated with an artifact</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="otherpage" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                  <xs:documentation>Additional page URLs that should be treated as part of this page for categorization purposes (used to infer/validate pages based on URL)</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:attribute name="url" type="xs:NMTOKEN" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="key" type="xs:NMTOKEN" use="required">
              <xs:annotation>
                <xs:documentation>The key used inside Jira to identify the page  This key must not be renamed and cannot be removed if it appears in any tracker item.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="name" type="Name" use="required">
              <xs:annotation>
                <xs:documentation>The name to display to users for the page.  This can change if the page is renamed</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="workgroup" type="WorkGroup" use="optional">
              <xs:annotation>
                <xs:documentation>The work group typically responsible for issues relating to this page</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="deprecated" type="xs:boolean" default="false">
              <xs:annotation>
                <xs:documentation>If true, indicates that the page can no longer be associated with newly raised issues, but it can still appear on old issues and be used in search</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="url" type="xs:NMTOKEN" use="optional">
              <xs:annotation>
                <xs:documentation>The primary url associated with this page (this may initially be the same as the key, but will change if the url changes)</xs:documentation>
              </xs:annotation>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="url" type="website" use="optional">
        <xs:annotation>
          <xs:documentation>The official URL for this specification.  Used when validating URLs</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="ciUrl" type="website" use="optional">
        <xs:annotation>
          <xs:documentation>The continuous integration build URL for this specification.  Used when validating URLs</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="ballotUrl" type="website" use="optional">
        <xs:annotation>
          <xs:documentation>The URL for the current/most recent ballot of this specification.  Used when validating URLs</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="gitUrl" type="website" use="optional">
        <xs:annotation>
          <xs:documentation>The base URL for the repository in which the source material for this specificaiton is maintained.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="defaultWorkgroup" type="WorkGroup" use="optional">
        <xs:annotation>
          <xs:documentation>The work group typically associated with issues raised against this specification if a more specific work group isn't determined based on pages or artifacts</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="defaultVersion" type="xs:NMTOKEN" use="required">
        <xs:annotation>
          <xs:documentation>The version to identify as the 'raised' version for an issue if not overridden by the submitter</xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
    <xs:key name="version-code">
      <xs:selector xpath="version"/>
      <xs:field xpath="@code"/>
    </xs:key>
    <xs:keyref name="version-code-default" refer="version-code">
      <xs:selector xpath="."/>
      <xs:field xpath="@defaultVersion"/>
    </xs:keyref>
    <xs:unique name="artifactPageExtension-value-unique">
      <xs:selector xpath="artifactPageExtension"/>
      <xs:field xpath="@value"/>
    </xs:unique>
    <xs:unique name="artifact-key-unique">
      <xs:selector xpath="artifact"/>
      <xs:field xpath="@key"/>
    </xs:unique>
    <xs:unique name="artifact-name-unique">
      <xs:selector xpath="artifact"/>
      <xs:field xpath="@name"/>
    </xs:unique>
    <xs:unique name="artifact-id-unique">
      <xs:selector xpath="artifact"/>
      <xs:field xpath="@id"/>
    </xs:unique>
    <xs:unique name="page-key-unique">
      <xs:selector xpath="page"/>
      <xs:field xpath="@key"/>
    </xs:unique>
    <xs:unique name="page-name-unique">
      <xs:selector xpath="page"/>
      <xs:field xpath="@name"/>
    </xs:unique>
    <xs:unique name="page-url-unique">
      <xs:selector xpath="page"/>
      <xs:field xpath="@url"/>
    </xs:unique>
    <xs:unique name="page-otherpage-url-unique">
      <xs:selector xpath="page/otherpage"/>
      <xs:field xpath="@url"/>
    </xs:unique>
  </xs:element>
  <xs:simpleType name="website">
    <xs:restriction base="xs:anyURI">
      <xs:pattern value="http(s)?://(\S)+[^/]"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Name">
    <xs:restriction base="xs:string">
      <xs:pattern value="[^\s]+([\s][^\s]+)*"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="NonEmptyString">
    <xs:restriction base="xs:string">
      <xs:pattern value="[^\s]+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== HL7/JIRA-Spec-Artifacts/xml/OTHER-arden-syntax.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification defaultWorkgroup="as" defaultVersion="3.0" url="http://www.hl7.org/documentcenter/public/ballots/2023JAN/downloads/Arden%20Syntax%203.0_PDF.zip" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/specification.xsd">
  <version code="3.0" deprecated="false"/>
  <page name="WHATâ€™S NEW IN VERSION 3.0" key="new"/>
  <page name="SCOPE" key="scope"/>
  <page name="REFERENCED DOCUMENTS" key="references"/>
  <page name="TERMINOLOGY" key="terminology"/>
  <page name="SIGNIFICANCE AND USE" key="significance"/>
  <page name="MLM FORMAT" key="mlm_format"/>
  <page name="SLOT DESCRIPTIONS" key="slot_descriptions"/>
  <page name="STRUCTURED SLOT SYNTAX" key="slot_syntax"/>
  <page name="DATA TYPES" key="data_types"/>
  <page name="OPERATOR DESCRIPTIONS" key="operator_descriptions"/>
  <page name="LOGIC SLOT" key="logic_slot"/>
  <page name="DATA SLOT and plan" key="data_slot"/>
  <page name="FHIR ENABLED DATA ACCESS" key="fhir_data_access"/>
  <page name="ACTION SLOT" key="action_slot"/>
  <page name="EVOKE SLOT" key="evoke_slot"/>
  <page name="Annexes" key="annexes"/>
</specification>

=== HL7/JIRA-Spec-Artifacts/xml/CDA-nutrition.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2020 rel. 2 sp1 (x64) (http://www.altova.com) by  (Cerner Corporation) -->
<specification defaultVersion="1.0" defaultWorkgroup="sd" url="http://www.hl7.org/implement/standards/product_brief.cfm?product_id=478" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/specification.xsd">
	<version url="http://www.hl7.org/implement/standards/product_brief.cfm?product_id=478" deprecated="false" code="1.0"/>
	<page url="http:www.hl7.orgimplementstandardsproduct_brief.cfmproduct_id478" key="ccdatemplatenutition" name="HL7 CDAÂ® R2 Implementation Guide: C-CDA R2.1 Supplemental Templates for Nutrition, Release 1 - US Realm"/>
	<page key="NA" name="(NA)"/>
	<page key="many" name="(many)"/>
	<page key="profiles" name="(profiles)"/>
	<page key="overview" name="Overview"/>
	<page key="usecases" name="Use Cases"/>
	<page key="documentation" name="Documentation" deprecated="true"/>
	<page key="index" name="Index" deprecated="true"/>
	<page key="narratives" name="Narrative Guidance"/>
	<page key="templates" name="Templates"/>
	<page key="figures" name="Figures and Examples"/>
	<page key="valuesets" name="Value sets"/>
	<page key="samplefiles" name="Sample Files"/>
	<page key="validationfiles" name="Validation Files"/>
	<page key="schematron" name="Schematron"/>
</specification>

=== HL7/JIRA-Spec-Artifacts/xml/FHIR-cdisc-lab.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification gitUrl="https://github.com/HL7/cdisc-lab" url="http://hl7.org/fhir/uv/cdisc-lab" ciUrl="http://build.fhir.org/ig/HL7/cdisc-lab" defaultWorkgroup="brr" defaultVersion="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/specification.xsd">
  <version code="1.0.0" url="https://hl7.org/fhir/uv/cdisc-lab/STU1"/>
  <version code="0.1" deprecated="true"/>
  <artifactPageExtension value="-definitions"/>
  <artifactPageExtension value="-examples"/>
  <artifactPageExtension value="-mappings"/>
  <page name="(NA)" key="NA"/>
  <page name="(many)" key="many"/>
  <page name="(profiles)" key="profiles"/>
  <page name="overview" key="overview"/>
  <page name="usecases" key="usecases"/>
</specification>

=== HL7/JIRA-Spec-Artifacts/xml/V2-vrdr.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification defaultWorkgroup="pher" defaultVersion="2.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/specification.xsd">
 <version code="2.0"/>
 <version code="2.1"/>
 <artifact name="MEDICAL CERTIFIER DEATH INFORMATION Profile Component" key="MCDIprofile" id="ADT/MCDI"/>
 <artifact name="FUNERAL DIRECTOR DEATH INFORMATION Profile Component" key="FDDIprofile" id="ADT/FDFDI"/>
 <artifact name="JURISDICTION DEATH INFORMATION Profile Component" key="JDIprofile" id="ADT/JDI"/>
 <artifact name="CODED CAUSE OF DEATH INFORMATION Profile Component" key="CCODIprofile" id="ADT/CCODI"/>
 <artifact name="CODED RACE AND ETHNICITY INFORMATION Profile Component" key="CREIprofile" id="ADT/CREI"/>
 <artifact name="IMMEDIATE DEATH NOTIFICATION Conformance Profile" key="IDNA04" id="ADT/IDNA04"/>
 <artifact name="CANCEL DEATH NOTIFICATION Conformance Profile" key="IDNA11" id="ADT/IDNA11"/>
 <artifact name="REPORT CASE IDENTIFIER Conformance Profile" key="CIAA04" id="ADT/CIAA04"/>
 <artifact name="REPORT CERTIFIER DEATH REGISTRATION Conformance Profile" key="MCDIA04" id="ADT/MCDIA04"/>
 <artifact name="REVISE CERTIFIER DEATH REGISTRATION Conformance Profile" key="MCDIA08" id="ADT/MCDIA08"/>
 <artifact name="CANCEL CERTIFIER DEATH REGISTRATION Conformance Profile" key="MCDIA11" id="ADT/MCDIA11"/>
 <artifact name="REPORT FUNERAL DIRECTOR DEATH INFORMATION Conformance Profile" key="FDDIA04" id="ADT/FDDIA04"/>
 <artifact name="REVISE FUNERAL DIRECTOR DEATH INFORMATION Conformance Profile" key="FDDIA08" id="ADT/FDDIA08"/>
 <artifact name="CANCEL FUNERAL DIRECTOR DEATH INFORMATION Conformance Profile" key="FDDIA11" id="ADT/FDDIA11"/>
 <artifact name="REPORT JURISDICTION DEATH REGISTRATION Conformance Profile" key="JDIA04" id="ADT/JDIA04"/>
 <artifact name="REVISE JURISDICTION DEATH REGISTRATION Conformance Profile" key="JDIA08" id="ADT/JDIA08"/>
 <artifact name="CANCEL JURISDICTION DEATH REGISTRATION Conformance Profile" key="JDIA11" id="ADT/JDIA11"/>
 <artifact name="REPORT VOID CERTIFICATE Conformance Profile" key="RVCA04" id="ADT/RVCA04"/>
 <artifact name="REPORT CODED CAUSE OF DEATH Conformance Profile" key="CCODA04" id="ADT/CCODA04"/>
 <artifact name="REVISE CODED CAUSE OF DEATH REPORT Conformance Profile" key="CCODA08" id="ADT/CCODA08"/>
 <artifact name="CANCEL CODED CAUSE OF DEATH REPORT Conformance Profile" key="CCODA11" id="ADT/CCODA11"/>
 <artifact name="REPORT CODED RACE AND ETHNICITY Conformance Profile" key="CREIA04" id="ADT/CREIA04"/>
 <artifact name="REVISE CODED RACE AND ETHNICITY REPORT Conformance Profile" key="CREIA08" id="ADT/CREIA08"/>
 <artifact name="ACKNOWLEDGEMENT Conformance Profile" key="ACK" id="ADT/ACK"/>
 <artifact name="REPORT CERTIFIER DEATH REGISTRATION Composite Profile" key="CP_MCDIA04" id="ADT/CP_MCDIA04"/>
 <artifact name="REVISE CERTIFIER DEATH REGISTRATION Composite Profile" key="CP_MCDIA08" id="ADT/CP_MCDIA08"/>
 <artifact name="REPORT DEMOGRAPHIC DEATH INFORMATION Composite Profile" key="CP_FDDIA04" id="ADT/CP_FDDIA04"/>
 <artifact name="REVISE DEMOGRAPHIC DEATH INFORMATION Composite Profile" key="CP_FDDIA08" id="ADT/CP_FDDIA08"/>
 <artifact name="REPORT JURISDICTION DEATH REGISTRATION Composite Profile" key="CP_JDIA04" id="ADT/CP_JDIA04"/>
 <artifact name="REVISE JURISDICTION DEATH REGISTRATION Composite Profile" key="CP_JDIA08" id="ADT/CP_JDIA08"/>
 <artifact name="CODED CAUSE OF DEATH Composite Profile" key="CP_CCODA04" id="ADT/CP_CCODA04"/>
 <artifact name="CODED CAUSE OF DEATH REPORT Composite Profile" key="CP_CCODA08" id="ADT/CP_CCODA08"/>
 <artifact name="CODED RACE AND ETHNICITY Composite Profile" key="CP_CREIA04" id="ADT/CP_CREIA04"/>
 <artifact name="CODED RACE AND ETHNICITY REPORT Composite Profile" key="CP_CREIA08" id="ADT/CP_CREIA08"/>
 <artifact name="ERR_DR Composite Profile" key="ERR_DR" id="ERR/DR"/>
 <artifact name="EVN_DR Composite Profile" key="EVN_DR" id="EVN/DR"/>
 <artifact name="MSA_DR Composite Profile" key="MSA_DR" id="MSA/DR"/>
 <artifact name="MSH_DR Composite Profile" key="MSH_DR" id="MSH/DR"/>
 <artifact name="OBX_DR Composite Profile" key="OBX_DR" id="OBX/DR"/>
 <artifact name="OBX_DR_CCODA04 Composite Profile" key="OBX_DR_CCODA04" id="OBX/DR_CCODA04"/>
 <artifact name="OBX_DR_CCODA08 Composite Profile" key="OBX_DR_CCODA08" id="OBX/DR_CCODA08"/>
 <artifact name="OBX_DR_CREIA04 Composite Profile" key="OBX_DR_CREIA04" id="OBX/DR_CREIA04"/>
 <artifact name="OBX_DR_CREIA08 Composite Profile" key="OBX_DR_CREIA08" id="OBX/DR_CREIA08"/>
 <artifact name="OBX_DR_DRA04 Composite Profile" key="OBX_DR_DRA04" id="OBX/DR_DRA04"/>
 <artifact name="OBX_DR_DRA08 Composite Profile" key="OBX_DR_DRA08" id="OBX/DR_DRA08"/>
 <artifact name="OBX_DR_FDDIA04 Composite Profile" key="OBX_DR_FDDIA04" id="OBX/DR_FDDIA04"/>
 <artifact name="OBX_DR_FDDIA08 Composite Profile" key="OBX_DR_FDDIA08" id="OBX/DR_FDDIA08"/>
 <artifact name="OBX_DR_JDIA04 Composite Profile" key="OBX_DR_JDIA04" id="OBX/DR_JDIA04"/>
 <artifact name="OBX_DR_JDIA08 Composite Profile" key="OBX_DR_JDIA08" id="OBX/DR_JDIA08"/>
 <artifact name="OBX_DR_MCDIA04 Composite Profile" key="OBX_DR_MCDIA04" id="OBX/DR_MCDIA04"/>
 <artifact name="OBX_DR_MCDIA08 Composite Profile" key="OBX_DR_MCDIA08" id="OBX/DR_MCDIA08"/>
 <artifact name="PDA_DR_JDI Composite Profile" key="PDA_DR_JDI" id="PDA/DR_JDI"/>
 <artifact name="PDA_DR_PSDI Composite Profile" key="PDA_DR_PSDI" id="PDA/DR_PSDI"/>
 <artifact name="PID_DR_CREI Composite Profile" key="PID_DR_CREI" id="PID/DR_CREI"/>
 <artifact name="PID_DR_DEM Composite Profile" key="PID_DR_DEM" id="PID/DR_DEM"/>
 <artifact name="PID_DR_ID Composite Profile" key="PID_DR_ID" id="PID/DR_ID"/>
 <artifact name="PID_DR_JDI Composite Profile" key="PID_DR_JDI" id="PID/DR_JDI"/>
 <artifact name="PID_DR_MCDI Composite Profile" key="PID_DR_MCDI" id="PID/DR_MCDI"/>
 <artifact name="PV1_DR Composite Profile" key="PV1_DR" id="PV1/DR"/>
 <artifact name="Value Sets" key="valuesets" id="VALUESET/SS"/>
 <artifact name="Data Type Flavors" key="datatypeflavors" id="DATATYPES/SS"/>
 <page name="Introduction" key="intro"/>
 <page name="Messaging Framework" key="msgframe"/>
 <page name="Message Components" key="msgcomp"/>
 <page name="Use Cases" key="usecases"/>
 <page name="References" key="references"/>
 <page name="Examples" key="examples"/>
 <page name="Other" key="other"/>
</specification>

=== HL7/JIRA-Spec-Artifacts/xml/V2-conformance.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- This data is just for testing purposes and is not complete -->
<specification defaultWorkgroup="cgit" defaultVersion="R1.0" url="http://www.hl7.org/implement/standards/product_brief.cfm?product_id=533" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/specification.xsd">
  <version code="R1.0"/>
  <page name="Introduction" key="introduction"/>
  <page name="Profile Levels" key="profilelevels"/>
  <page name="V2 Implementation Guides" key="implementationguides"/>
  <page name="Message Profiles" key="messageprofiles"/>
  <page name="Constraints" key="constraints"/>
  <page name="Vocabulary Constraints" key="vocabconstraints"/>
  <page name="Profile Constraints" key="profileconstraints"/>
  <page name="Pairing Sender and Receiver Profiles" key="senderreceiver"/>
  <page name="Profile Documentation" key="profiledocumentation"/>
  <page name="Computable Document Definitions" key="computabledefinitions"/>
  <page name="Glossary" key="glossary"/>
  <page name="Appendix A" key="appendixa"/>
  <page name="Appendix B" key="appendixb"/>
  <page name="Other" key="other"/>
  <page key="TBD" name="TBD"/>
</specification>

=== HL7/JIRA-Spec-Artifacts/xml/FHIR-us-sdoh-cc.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification gitUrl="https://github.com/HL7/sdoh-cc" 
  url="http://hl7.org/fhir/us/sdoh-cc" 
  ciUrl="http://build.fhir.org/ig/HL7/sdoh-cc" 
  defaultWorkgroup="pc" defaultVersion="0.0.4" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/specification.xsd">
  <version code="0.0.4"/>
  <artifactPageExtension value="-narrative"/>
  <artifactPageExtension value="-artifact"/>
  <page name="(NA)" key="NA"/>
  <page name="(many)" key="many"/>
  <page name="(homePage)" key="homePage"/>
  <page name="(profiles)" key="profiles"/>
</specification>

=== HL7/JIRA-Spec-Artifacts/xml/CDA-phcaserpt.xml
<?xml version="1.1" encoding="UTF-8"?>
<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="schemas/specification.xsd" defaultVersion="3.1.1"
	defaultWorkgroup="sd" url="https://github.com/HL7/CDA-phcaserpt">
  <version code="4.0.0-ballot" deprecated="false"/>
  <version code="3.1.1" deprecated="false"/>
  <version code="1.3.1" deprecated="true"/>
	<version code="1.3.0" deprecated="true"/>
	<version code="1.2.0" deprecated="true"/>
	<version code="1.1.1" deprecated="false"/>
	<page key="NA" name="(NA)"/>
	<page key="many" name="(many)"/>
	<page key="usecases" name="Use Cases"/>
	<page key="narratives" name="Narrative Guidance"/>
	<page key="templates" name="Templates"/>
	<page key="figures-examples" name="Figures and Examples"/>
	<page key="valuesets" name="Value sets"/>
	<page key="samplefiles" name="Sample Files"/>
	<page key="schematron" name="Schematron Validation Files"/>
	<page key="TBD" name="TBD"/>
</specification>

=== HL7/JIRA-Spec-Artifacts/xml/CDA-pharm.xml
<?xml version="1.1" encoding="UTF-8"?>
<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/specification.xsd" defaultVersion="1.1.0" defaultWorkgroup="pharm" url="http://www.hl7.org/implement/standards/product_brief.cfm?product_id=514">
	<!-- new version 1.2.0 added -->
	<version code="1.2.0" deprecated="false"/>
	<!-- -->
	<version code="1.2.0-ballot" deprecated="true"/>
	<version code="1.1.0" deprecated="true"/>
	<version code="1.0.0" deprecated="true"/>


	<artifact id="2.16.840.1.113883.10.21.4.4" name="UV ClinicalStatement Encounter" key="UVClinicalStatementMinimalEncounter"/>
	<artifact id="2.16.840.1.113883.10.21.4.3" name="UV ClinicalStatement Observation" key="UVClinicalStatementMinimalObservation"/>
	<artifact id="2.16.840.1.113883.10.21.4.12" name="UV Comment Activity" key="UVCommentactivity"/>
	<artifact id="2.16.840.1.113883.10.21.4.9" name="UV Dispense Event Reference" key="UVDispenseEventReference"/>
	<artifact id="2.16.840.1.113883.10.21.4.2" name="UV Dispense Request" key="UVDispenseRequest"/>
	<artifact id="2.16.840.1.113883.10.21.4.18" name="UV Ingredient" key="UVIngredient"/>
	<artifact id="2.16.840.1.113883.10.21.4.15" name="UV Medication Dispense" key="UVMedicationDispense"/>
	<artifact id="2.16.840.1.113883.10.21.4.11" name="UV Medication Information (detail)" key="UVMedicationInformationdetail"/>
	<artifact id="2.16.840.1.113883.10.21.4.10" name="UV Medication Information (simple)" key="UVMedicationInformationsimple"/>
	<artifact id="2.16.840.1.113883.10.21.4.8" name="UV Medication Order Reference" key="UVMedicationOrderReference"/>
	<artifact id="2.16.840.1.113883.10.21.4.13" name="UV Medication Administration" key="UVMedicationadministration"/>
	<artifact id="2.16.840.1.113883.10.21.4.7" name="UV Medication Statement" key="UVMedicationstatement"/>
	<artifact id="2.16.840.1.113883.10.21.4.6" name="UV Subordinate Substance Administration" key="UVSubordinateadministration"/>
	<artifact id="2.16.840.1.113883.10.21.4.1" name="UV Medication Order" key="UVSubstanceadministrationrequest"/>
	<artifact id="2.16.840.1.113883.10.21.4.14" name="UV Substitution Event Adminstration" key="UVSubstitutionEventAdministration"/>
	<artifact id="2.16.840.1.113883.10.21.4.5" name="UV Substitution Permission" key="UVSubstitutionPermission"/>
	<artifact id="2.16.840.1.113883.10.21.4.17" name="UV Content" key="UVasContent"/>
	<artifact id="2.16.840.1.113883.10.21.4.19" name="UV Generalized Medicine Class" key="UVgeneralizedMedicineClass"/>
	<artifact id="2.16.840.1.113883.10.21.9.1" name="UV Use Period" key="Useperiod"/>
	<artifact id="2.16.840.1.113883.11.21.2" name="ActStatusActiveCompletedAbortedSuspended" key="ActStatusCodeActiveCompletedAbortedSuspended"/>
	<artifact id="2.16.840.1.113883.11.21.1" name="Medication Time Units (UCUM)" key="MedicationTimeUnits"/>
	<artifact id="2.16.840.1.113883.11.21.4" name="Mood Code Evn Int Rqo" key="MoodCodeEvnIntRqo"/>
	<artifact id="2.16.840.1.113883.11.21.5" name="Unknown or absent medication" key="Unknownorabsentmedication"/>



	<page key="NA" name="(NA)"/>
	<page key="many" name="(many)"/>
	<page key="usecases" name="Use Cases"/>
	<page key="narratives" name="Narrative Guidance"/>
	<page key="templates" name="Templates"/>
	<page key="figures-examples" name="Figures and Examples"/>
	<page key="valuesets" name="Value sets"/>
	<page key="samplefiles" name="Sample Files"/>
	<page key="schematron" name="Schematron Validation Files"/>
	<page key="TBD" name="TBD"/>

</specification>
